// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using sopman.Data;
using System;

namespace sopman.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180122103510_removetop")]
    partial class removetop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
